// <auto-generated />
using System;
using LeadManagement.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeadManagement.Web.Migrations
{
    [DbContext(typeof(LeadManagementDbContext))]
    [Migration("20260715090835_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LeadManagement.Web.Domain.Entities.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Email");

                    b.HasIndex("StatusId");

                    b.ToTable("Leads", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Company = "Northstar Digital",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 25, 8, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "aisha.khan@example.com",
                            FirstName = "Aisha",
                            LastName = "Khan",
                            Phone = "+971 50 555 0101",
                            RowVersion = new byte[0],
                            StatusId = 1
                        },
                        new
                        {
                            Id = 2,
                            Company = "BluePeak Logistics",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 10, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "david.brown@example.com",
                            FirstName = "David",
                            LastName = "Brown",
                            Phone = "+971 50 555 0102",
                            RowVersion = new byte[0],
                            StatusId = 2
                        },
                        new
                        {
                            Id = 3,
                            Company = "Vertex Consulting",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 22, 13, 45, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "maria.garcia@example.com",
                            FirstName = "Maria",
                            LastName = "Garcia",
                            Phone = "+971 50 555 0103",
                            RowVersion = new byte[0],
                            StatusId = 3
                        },
                        new
                        {
                            Id = 4,
                            Company = "Crescent Holdings",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 18, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "omar.ali@example.com",
                            FirstName = "Omar",
                            LastName = "Ali",
                            Phone = "+971 50 555 0104",
                            RowVersion = new byte[0],
                            StatusId = 4
                        },
                        new
                        {
                            Id = 5,
                            Company = "Atlas Retail Group",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 27, 16, 20, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "sophie.turner@example.com",
                            FirstName = "Sophie",
                            LastName = "Turner",
                            Phone = "+971 50 555 0105",
                            RowVersion = new byte[0],
                            StatusId = 1
                        });
                });

            modelBuilder.Entity("LeadManagement.Web.Domain.Entities.LeadActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("FromStatusId")
                        .HasColumnType("int");

                    b.Property<int>("LeadId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ToStatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FromStatusId");

                    b.HasIndex("ToStatusId");

                    b.HasIndex("LeadId", "ChangedAt");

                    b.ToTable("LeadActivities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChangedAt = new DateTimeOffset(new DateTime(2026, 6, 26, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatusId = 1,
                            LeadId = 2,
                            Note = "Status changed by user",
                            ToStatusId = 2
                        },
                        new
                        {
                            Id = 2,
                            ChangedAt = new DateTimeOffset(new DateTime(2026, 6, 23, 9, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatusId = 1,
                            LeadId = 3,
                            Note = "Status changed by user",
                            ToStatusId = 2
                        },
                        new
                        {
                            Id = 3,
                            ChangedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 14, 10, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatusId = 2,
                            LeadId = 3,
                            Note = "Status changed by user",
                            ToStatusId = 3
                        },
                        new
                        {
                            Id = 4,
                            ChangedAt = new DateTimeOffset(new DateTime(2026, 6, 21, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FromStatusId = 3,
                            LeadId = 4,
                            Note = "Status changed by user",
                            ToStatusId = 4
                        });
                });

            modelBuilder.Entity("LeadManagement.Web.Domain.Entities.LeadStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("varchar(7)")
                        .HasDefaultValue("#0D6EFD");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("IsActive", "DisplayOrder");

                    b.ToTable("Statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorCode = "#0D6EFD",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "New"
                        },
                        new
                        {
                            Id = 2,
                            ColorCode = "#FFC107",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Contacted"
                        },
                        new
                        {
                            Id = 3,
                            ColorCode = "#198754",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Qualified"
                        },
                        new
                        {
                            Id = 4,
                            ColorCode = "#6C757D",
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "Closed"
                        });
                });

            modelBuilder.Entity("LeadManagement.Web.Domain.Entities.Lead", b =>
                {
                    b.HasOne("LeadManagement.Web.Domain.Entities.LeadStatus", "Status")
                        .WithMany("Leads")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("LeadManagement.Web.Domain.Entities.LeadActivity", b =>
                {
                    b.HasOne("LeadManagement.Web.Domain.Entities.LeadStatus", "FromStatus")
                        .WithMany("ActivitiesFrom")
                        .HasForeignKey("FromStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeadManagement.Web.Domain.Entities.Lead", "Lead")
                        .WithMany("Activities")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeadManagement.Web.Domain.Entities.LeadStatus", "ToStatus")
                        .WithMany("ActivitiesTo")
                        .HasForeignKey("ToStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromStatus");

                    b.Navigation("Lead");

                    b.Navigation("ToStatus");
                });

            modelBuilder.Entity("LeadManagement.Web.Domain.Entities.Lead", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("LeadManagement.Web.Domain.Entities.LeadStatus", b =>
                {
                    b.Navigation("ActivitiesFrom");

                    b.Navigation("ActivitiesTo");

                    b.Navigation("Leads");
                });
#pragma warning restore 612, 618
        }
    }
}
